// Code generated by goctl. DO NOT EDIT!
// Source: base_rpc.proto

package baserpc

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	GetPkgConfigReq struct {
		PkgName string `json:"pkg_name,omitempty"`
		Section string `json:"section,omitempty"`
		Key     string `json:"key,omitempty"`
	}

	GetPkgConfigResp struct {
		Value string `json:"value,omitempty"`
	}

	GetPkgSectionConfigReq struct {
		PkgName string `json:"pkg_name,omitempty"`
		Section string `json:"section,omitempty"`
	}

	GetPkgSectionConfigResp struct {
		Items []*PkgConfig `json:"items,omitempty"`
	}

	GetSystemConfigReq struct {
		Section string   `json:"section,omitempty"`
		Keys    []string `json:"keys,omitempty"`
	}

	GetSystemConfigRes struct {
		Items []*SystemConfig `json:"items,omitempty"`
	}

	IsBanReq struct {
		UserId  int64  `json:"user_id,omitempty"`
		GuestId string `json:"guest_id,omitempty"`
	}

	IsBanRes struct {
		IsBan bool `json:"isBan,omitempty"`
	}

	PkgConfig struct {
		Key   string `json:"key,omitempty"`
		Value string `json:"value,omitempty"`
	}

	SystemConfig struct {
		Section  string `json:"section,omitempty"`
		Key      string `json:"key,omitempty"`
		Category string `json:"category,omitempty"`
		Value    string `json:"value,omitempty"`
	}
)
