// Code generated by goctl. DO NOT EDIT!
// Source: base_rpc.proto

package baserpc

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	GetPkgConfigReq struct {
		PkgName string `json:"pkg_name,omitempty"`
		Section string `json:"section,omitempty"`
		Key     string `json:"key,omitempty"`
	}

	GetPkgConfigResp struct {
		Value string `json:"value,omitempty"`
	}

	GetPkgSectionConfigReq struct {
		PkgName string `json:"pkg_name,omitempty"`
		Section string `json:"section,omitempty"`
	}

	GetPkgSectionConfigResp struct {
		Items []*PkgConfig `json:"items,omitempty"`
	}

	PkgConfig struct {
		Key   string `json:"key,omitempty"`
		Value string `json:"value,omitempty"`
	}
)
