// Code generated by goctl. DO NOT EDIT!
// Source: user_rpc.proto

package userrpc

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	AddUserReq struct {
		Avatar string `json:"avatar,omitempty"`
	}

	AddUserRes struct {
		User *UserInfo `json:"user,omitempty"`
	}

	GetUserReq struct {
		UserId int64 `json:"user_id,omitempty"`
	}

	GetUserRes struct {
		User *UserInfo `json:"user,omitempty"`
	}

	UserInfo struct {
		UserId         int64  `json:"user_id,omitempty"`
		AccessToken    string `json:"access_token,omitempty"`
		Avatar         string `json:"avatar,omitempty"`
		CreateTimeUnix int64  `json:"create_time_unix,omitempty"`
	}
)
