// Code generated by goctl. DO NOT EDIT!
// Source: user_rpc.proto

package userrpc

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	ActionPoint struct {
		PayChannel    int64 `json:"pay_channel,omitempty"`
		VipPromotion  int64 `json:"vip_promotion,omitempty"`
		CoinPromotion int64 `json:"coin_promotion,omitempty"`
	}

	AddActionPointReq struct {
		UserId             int64 `json:"user_id,omitempty"`
		PayChannelPoint    int64 `json:"pay_channel_point,omitempty"`
		VipPromotionPoint  int64 `json:"vip_promotion_point,omitempty"`
		CoinPromotionPoint int64 `json:"coin_promotion_point,omitempty"`
	}

	AddActionPointRes struct {
		UserExt *UserExt `json:"user_ext,omitempty"`
	}

	AddUserReq struct {
		Avatar string `json:"avatar,omitempty"`
	}

	AddUserRes struct {
		User *UserInfo `json:"user,omitempty"`
	}

	GetUserReq struct {
		UserId int64 `json:"user_id,omitempty"`
	}

	GetUserRes struct {
		User *UserInfo `json:"user,omitempty"`
	}

	GuestInfo struct {
		GuestId     string `json:"guest_id,omitempty"`
		GuestName   string `json:"guest_name,omitempty"`
		Platform    string `json:"platform,omitempty"`
		AndroidId   string `json:"android_id,omitempty"`
		AppVersion  string `json:"app_version,omitempty"`
		Country     string `json:"country,omitempty"`
		Imei        string `json:"imei,omitempty"`
		Channel     string `json:"channel,omitempty"`
		CampaignId  string `json:"campaign_id,omitempty"`
		UserChannel string `json:"user_channel,omitempty"`
	}

	GuestInitReq struct {
		GuestId     string `json:"guest_id,omitempty"`
		Platform    string `json:"platform,omitempty"`
		AndroidId   string `json:"android_id,omitempty"`
		AppVersion  string `json:"app_version,omitempty"`
		Country     string `json:"country,omitempty"`
		Imei        string `json:"imei,omitempty"`
		Channel     string `json:"channel,omitempty"`
		CampaignId  string `json:"campaign_id,omitempty"`
		UserChannel string `json:"user_channel,omitempty"`
	}

	GuestInitRes struct {
		Guest *GuestInfo `json:"guest,omitempty"`
	}

	GuestLoginReq struct {
		GuestId     string `json:"guest_id,omitempty"`
		Platform    string `json:"platform,omitempty"`
		Country     string `json:"country,omitempty"`
		Channel     string `json:"channel,omitempty"`
		UserChannel string `json:"user_channel,omitempty"`
		PkgName     string `json:"pkg_name,omitempty"`
	}

	GuestLoginRes struct {
		User *UserInfo `json:"user,omitempty"`
	}

	PageAnchorRecommendReq struct {
		UserId int64 `json:"user_id,omitempty"`
		Skip   int64 `json:"skip,omitempty"`
		Limit  int64 `json:"limit,omitempty"`
	}

	PageAnchorRecommendRes struct {
		Anchors []*UserInfo `json:"anchors,omitempty"`
	}

	UserExt struct {
		UserId      int64        `json:"user_id,omitempty"`
		ActionPoint *ActionPoint `json:"action_point,omitempty"`
	}

	UserInfo struct {
		UserId         int64  `json:"user_id,omitempty"`
		AccessToken    string `json:"access_token,omitempty"`
		NickName       string `json:"nick_name,omitempty"`
		LoginName      string `json:"login_name,omitempty"`
		UserRole       string `json:"user_role,omitempty"`
		Country        string `json:"country,omitempty"`
		Channel        string `json:"channel,omitempty"`
		UserChannel    string `json:"user_channel,omitempty"`
		Avatar         string `json:"avatar,omitempty"`
		RegGuestId     string `json:"reg_guest_id,omitempty"`
		RegPkgName     string `json:"reg_pkg_name,omitempty"`
		CreateTimeUnix int64  `json:"create_time_unix,omitempty"`
	}
)
