// Code generated by goctl. DO NOT EDIT!
// Source: event_rpc.proto

package main

import (
	"flag"
	"fmt"

	"frozen-go-project/rpc/event-rpc/internal/config"
	"frozen-go-project/rpc/event-rpc/internal/server"
	"frozen-go-project/rpc/event-rpc/internal/svc"
	event_rpc "frozen-go-project/rpc/event-rpc/pb"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/event-rpc.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	eventRpcSrv := server.NewEventRpcServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		event_rpc.RegisterEventRpcServer(grpcServer, eventRpcSrv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
