// Code generated by goctl. DO NOT EDIT!
// Source: base_rpc.proto

package server

import (
	"context"

	"frozen-go-project/rpc/base-rpc/internal/logic"
	"frozen-go-project/rpc/base-rpc/internal/svc"
	base_rpc "frozen-go-project/rpc/base-rpc/pb"
)

type BaseRpcServer struct {
	svcCtx *svc.ServiceContext
}

func NewBaseRpcServer(svcCtx *svc.ServiceContext) *BaseRpcServer {
	return &BaseRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *BaseRpcServer) GetPkgConfig(ctx context.Context, in *base_rpc.GetPkgConfigReq) (*base_rpc.GetPkgConfigResp, error) {
	l := logic.NewGetPkgConfigLogic(ctx, s.svcCtx)
	return l.GetPkgConfig(in)
}

func (s *BaseRpcServer) GetPkgSectionConfig(ctx context.Context, in *base_rpc.GetPkgSectionConfigReq) (*base_rpc.GetPkgSectionConfigResp, error) {
	l := logic.NewGetPkgSectionConfigLogic(ctx, s.svcCtx)
	return l.GetPkgSectionConfig(in)
}

func (s *BaseRpcServer) GetSystemConfigs(ctx context.Context, in *base_rpc.GetSystemConfigReq) (*base_rpc.GetSystemConfigRes, error) {
	l := logic.NewGetSystemConfigsLogic(ctx, s.svcCtx)
	return l.GetSystemConfigs(in)
}
