// Code generated by goctl. DO NOT EDIT!
// Source: test_rpc.proto

package server

import (
	"context"

	"frozen-go-project/rpc/test-rpc/internal/logic"
	"frozen-go-project/rpc/test-rpc/internal/svc"
	"frozen-go-project/rpc/test-rpc/test_rpc"
)

type TestRpcServer struct {
	svcCtx *svc.ServiceContext
}

func NewTestRpcServer(svcCtx *svc.ServiceContext) *TestRpcServer {
	return &TestRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *TestRpcServer) TestTest(ctx context.Context, in *test_rpc.TestReq) (*test_rpc.TestRes, error) {
	l := logic.NewTestTestLogic(ctx, s.svcCtx)
	return l.TestTest(in)
}
