// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type CommonParams struct {
	UserId int64 `form:"userId,optional"`
}

type CommonResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}
