// Code generated by goctl. DO NOT EDIT!
// Source: test_rpc.proto

package main

import (
	"flag"
	"fmt"
	"github.com/golang/protobuf/proto"

	"frozen-go-project/rpc/test-rpc/internal/config"
	"frozen-go-project/rpc/test-rpc/internal/server"
	"frozen-go-project/rpc/test-rpc/internal/svc"
	"frozen-go-project/rpc/test-rpc/test_rpc"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/testrpc.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewTestRpcServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		test_rpc.RegisterTestRpcServer(grpcServer, srv)
	})
	defer s.Stop()
	proto.Marshal(&test_rpc.TestReq{
		XXX_NoUnkeyedLiteral: struct{}{},
		XXX_unrecognized:     nil,
		XXX_sizecache:        0,
	})

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
