// Code generated by goctl. DO NOT EDIT!
// Source: base_rpc.proto

package main

import (
	"flag"
	"fmt"

	"frozen-go-project/rpc/base-rpc/internal/config"
	"frozen-go-project/rpc/base-rpc/internal/server"
	"frozen-go-project/rpc/base-rpc/internal/svc"
	base_rpc "frozen-go-project/rpc/base-rpc/pb"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/base-rpc.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	baseRpcSrv := server.NewBaseRpcServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		base_rpc.RegisterBaseRpcServer(grpcServer, baseRpcSrv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
